author: eccentric_nz
database: false
description: Makes gamey rotten zombie flesh safe to eat by freshening it up with
  a mixture of herbs!
main: me.eccentric_nz.plugins.deputrifier.Deputrifier
name: Deputrifier
startup: postworld
dev-url: http://dev.bukkit.org/server-mods/deputrifier
version: '1.1'
permissions:
   deputrifier.use:
      description: Allow players to change rotten flesh into beef.
      default: op
   deputrifier.toggle:
      description: Allow players to toggle the enable_chest or enable_craft config option on or off.
      default: op
commands:
  dptoggle:
    aliases: dpt
    description: Toggle the enable_chest or enable_craft config option on or off.
    usage: /<command> [chest|craft]
    permission: deputrifier.toggle
    permission-message: You don't have the permission to toggle Deputrifier on or off.
